const data = {
  members: [
    {
      id: "1",
      title: "Senator, 2nd Class",
      first_name: "Lamar",
      last_name: "Alexander",
      party: "R",
      gender: "M",
    },
    {
      id: "2",
      title: "Senator, 2nd Class",
      first_name: "Alex",
      last_name: "villecco",
      party: "4",
      gender: "5",
    },
    {
      id: "3",
      title: "Senator, 2nd Class",
      first_name: "John",
      last_name: "SnoW",
      party: "4",
      gender: "5",
    },
    {
      id: "4",
      title: "Senator, 2nd Class",
      first_name: "Johnathan",
      last_name: "Villa",
      party: "4",
      gender: "5",
    },
    {
      id: "5",
      title: "Senator, 2nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "6",
      title: "Senator, 6nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "7",
      title: "Senator, 2nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "8",
      title: "Senator, 1nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "9",
      title: "Senator, 2nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "10",
      title: "Senator, 4nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "11",
      title: "Senator, 5nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "12",
      title: "Senator, 6nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "13",
      title: "Senator, 3nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "14",
      title: "Senator, 4nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "15",
      title: "Senator, 3nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
    {
      id: "16",
      title: "Senator, 2nd Class",
      first_name: "22222",
      last_name: "33333",
      party: "4",
      gender: "5",
    },
  ],
};

export default data;
